CREATE TABLE IF NOT EXISTS users (
  email VARCHAR(190) NOT NULL PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(80) NOT NULL,
  name VARCHAR(190) NOT NULL,
  department VARCHAR(190) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_role (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS academic_years (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS academic_year_semesters (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  academic_year_id VARCHAR(64) NOT NULL,
  sem TINYINT UNSIGNED NOT NULL,
  subjects_json LONGTEXT NOT NULL,
  UNIQUE KEY uq_academic_year_semester (academic_year_id, sem),
  CONSTRAINT fk_year_semesters_year
    FOREIGN KEY (academic_year_id) REFERENCES academic_years(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS assessment_types (
  type VARCHAR(120) NOT NULL PRIMARY KEY,
  max_marks DECIMAL(10,2) NOT NULL,
  weightage DECIMAL(10,2) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS grading_scheme (
  grade VARCHAR(16) NOT NULL PRIMARY KEY,
  points DECIMAL(10,2) NOT NULL,
  min_marks DECIMAL(10,2) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS classes (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  grade INT NOT NULL,
  section VARCHAR(10) NOT NULL,
  students_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS subjects (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  code VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_subject_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS students (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  prn VARCHAR(64) NOT NULL,
  academic_year VARCHAR(64) NOT NULL,
  current_semester TINYINT UNSIGNED NOT NULL,
  email VARCHAR(190) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_student_prn (prn),
  INDEX idx_students_year (academic_year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS faculty (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  department VARCHAR(190) DEFAULT NULL,
  email VARCHAR(190) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS faculty_subjects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  faculty_id VARCHAR(64) NOT NULL,
  subject_name VARCHAR(190) NOT NULL,
  INDEX idx_faculty_subjects_faculty (faculty_id),
  CONSTRAINT fk_faculty_subjects_faculty
    FOREIGN KEY (faculty_id) REFERENCES faculty(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(64) NOT NULL,
  subject VARCHAR(190) NOT NULL,
  assessment_type VARCHAR(120) NOT NULL,
  marks DECIMAL(10,2) NOT NULL,
  max_marks DECIMAL(10,2) NOT NULL,
  semester TINYINT UNSIGNED NOT NULL,
  entry_date DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_marks_entry (student_id, subject, assessment_type, semester),
  INDEX idx_marks_subject (subject),
  INDEX idx_marks_semester (semester),
  CONSTRAINT fk_marks_student
    FOREIGN KEY (student_id) REFERENCES students(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_time DATETIME NOT NULL,
  user_name VARCHAR(190) NOT NULL,
  action_name VARCHAR(190) NOT NULL,
  details TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_logs_event_time (event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS face_profiles (
  email VARCHAR(190) NOT NULL PRIMARY KEY,
  profile_id VARCHAR(120) NOT NULL,
  user_name VARCHAR(190) NOT NULL,
  recorded_at DATETIME NOT NULL,
  features_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
